server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server-registry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server-registry:8761/eureka/